// flow-typed signature: ca45b4282f89198781e51012d26f41bd
// flow-typed version: <<STUB>>/mocha-loader_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-loader/EnhancedMocha' {
  declare module.exports: any;
}

declare module 'mocha-loader/start' {
  declare module.exports: any;
}

declare module 'mocha-loader/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-loader/EnhancedMocha.js' {
  declare module.exports: $Exports<'mocha-loader/EnhancedMocha'>;
}
declare module 'mocha-loader/index' {
  declare module.exports: $Exports<'mocha-loader'>;
}
declare module 'mocha-loader/index.js' {
  declare module.exports: $Exports<'mocha-loader'>;
}
declare module 'mocha-loader/start.js' {
  declare module.exports: $Exports<'mocha-loader/start'>;
}
declare module 'mocha-loader/web.js' {
  declare module.exports: $Exports<'mocha-loader/web'>;
}
